-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.cards
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    label text COLLATE pg_catalog."default" NOT NULL,
    type smallint NOT NULL,
    "chargingDate" smallint,
    "linkedAccount" uuid NOT NULL,
    CONSTRAINT cards_pkey PRIMARY KEY (id),
    CONSTRAINT "cards_linkedAccount_fkey" FOREIGN KEY ("linkedAccount")
        REFERENCES public.accounts (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.cards
    OWNER to postgres;

GRANT ALL ON TABLE public.cards TO anon;

GRANT ALL ON TABLE public.cards TO authenticated;

GRANT ALL ON TABLE public.cards TO postgres;

GRANT ALL ON TABLE public.cards TO service_role;
